### ISSUE TITLE
Persistent storage is hard in kubernetes

### ISSUE THREAD

**Issue by martinszy** [bitnami/bitnami-docker-matomo#19]
I used komposer to transform this docker-composer.yaml into a kubernetes yaml, but it had many errors. And then creating the storage is fatally complicated.

**Comment by juan131** [comment]
Hi @martinszy 

Could you please share with us the Kubernetes Yaml files you're trying to use to deploy Matomo on K8s? I'll take a look at them and help you to debug why it's failing.

**Comment by martinszy** [comment]
this is what I got from this github

 cat docker-compose.yaml 
version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  application:
    image: 'bitnami/matomo:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'matomo_data:/bitnami'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local


Then I run  kompose convert

And I get several files:
application-deployment.yaml  application-service.yaml mariadb-deployment.yaml  matomo-mariadb-data-persistentvolumeclaim.yaml  matomo-matomo-data-persistentvolumeclaim.yaml

I put them all together in a single file split by --- and started getting and correcting errors.
This is all the files:
https://gist.github.com/martinszy/6178cbe61968d027b3229ae578ba351c

**Comment by juan131** [comment]
The yaml files you shared are not creating a Service for MariaDB. Therefore, Matomo will be unable to connect to the MariaDB service.

Could you try with the ones below?

```
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
    service: database
  name: matomo-mariadb
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app: mariadb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mariadb
    service: database
  name: matomo-mariadb
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_DATABASE
          value: bitnami_matomo
        - name: MARIADB_USER
          value: bn_matomo
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: matomo-mariadb
        image: bitnami/mariadb:latest
        livenessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: mariadb
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - mysqladmin
            - ping
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /bitnami/mariadb
          name: mariadb-data
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      volumes:
      - name: mariadb-data
        persistentVolumeClaim:
          claimName: mariadb-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: matomo
    service: frontend
  name: matomo
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: matomo
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: matomo
    service: frontend
  name: matomo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: matomo
    spec:
      containers:
      - env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MARIADB_HOST
          value: matomo-mariadb
        - name: MARIADB_PORT_NUMBER
          value: "3306"
        - name: MATOMO_DATABASE_NAME
          value: bitnami_matomo
        - name: MATOMO_DATABASE_USER
          value: bn_matomo
        - name: MATOMO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-password
              name: matomo-mariadb
        image: bitnami/matomo:latest
        imagePullPolicy: Always
        name: matomo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - mountPath: /bitnami
          name: matomo-data
      restartPolicy: Always
      volumes:
      - name: matomo-data
        persistentVolumeClaim:
          claimName: matomo-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: matomo
    service: frontend
  name: matomo-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mariadb
    service: database
  name: mariadb-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
data:
  mariadb-password: aE5lYjdhVmtZdw==
kind: Secret
metadata:
  name: matomo-mariadb
type: Opaque
```

**Comment by martinszy** [comment]
For pod matomo-mariadb in describe I get

>   Warning  FailedScheduling  1m (x2 over 1m)   default-scheduler  persistentvolumeclaim "mariadb-data" not found
>  Warning  FailedScheduling  14s (x7 over 1m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 3 times)

And for matomo
>   Warning  FailedScheduling  2m (x2 over 2m)   default-scheduler  persistentvolumeclaim "matomo-data" not found
>  Warning  FailedScheduling  0s (x13 over 2m)  default-scheduler  pod has unbound PersistentVolumeClaims (repeated 3 times)

Also I don't see the Ingress part that is needed to have a public domain.

I add it here so we can include it in the final version:

```
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: matomo
  namespace: default
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/limit-connections: "10"
    ingress.kubernetes.io/enable-cors: "true"
    # ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - matomo.domain.com
    secretName: matomo-tls
  rules:
  - host: matomo.domain.com
    http:
      paths:
      - path: /
        backend:
          serviceName: matomo
          servicePort: 80
```
