### ISSUE TITLE
Error postInstallation Timeout to mariadb

### ISSUE THREAD

**Issue by dchen71** [bitnami/bitnami-docker-matomo#29]
I am having an issue trying to use docker compose to host both of the mariadb and matomo. I tried following the tutorial and can load the containers, however matomo is not being able to connect to the database. Unfortunately, port 80 and 443 are already taken so I had to change them otherwise the compose and the example compose are very similar. Does anyone have any clue what the error I am encountering is? The relevant logs and files are included in the bottom.

**Version**

- `docker-compose.yml`:

```
version: '2'
services:
  mariadb:
    user: root
    command: chown -R 1001:1001 /bitnami/mariadb
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/directory/piwik/mariadb:/bitnami/mariadb'
  matomo:
    image: 'bitnami/matomo:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6999:80'
      - '6998:443'
    depends_on:
      - mariadb
    volumes:
      - '/directory/piwik/matomo_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local

```

- Output of `docker-compose logs`:
```
Attaching to piwik_matomo_1, piwik_mariadb_1
mariadb_1  | 
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  | 
mariadb_1  | 
matomo_1   | 
matomo_1   | Welcome to the Bitnami matomo container
matomo_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   | 
matomo_1   | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo_1   | nami    INFO  Initializing apache
matomo_1   | apache  INFO  ==> Reconfiguring PID file location...
matomo_1   | apache  INFO  ==> Configuring dummy certificates...
matomo_1   | nami    INFO  apache successfully initialized
matomo_1   | nami    INFO  Initializing php
matomo_1   | nami    INFO  php successfully initialized
matomo_1   | nami    INFO  Initializing mysql-client
matomo_1   | nami    INFO  mysql-client successfully initialized
matomo_1   | nami    INFO  Initializing libphp
matomo_1   | nami    INFO  libphp successfully initialized
matomo_1   | nami    INFO  Initializing matomo
matomo_1   | matomo  INFO  Preparing PHP environment...
matomo_1   | matomo  INFO  Preparing matomo environment...
matomo_1   | mysql-c INFO  Trying to connect to MySQL server
matomo_1   | Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
```

- Output of `docker version`:

```
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        6247962
 Built:             Sun Feb 10 04:13:27 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```

- Output of `docker info`:

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 5
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-957.1.3.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.6 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.91GiB
Name: blahblahblah
ID: IATF:5HZZ:JKNA:2BMB:BF6C:37LS:6SU3:A4XU:RNZG:ZHVN:JHKR:GEXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Comment by marcosbc** [comment]
Hi @dchen71, it seems you applied a set proper ownership to create the mariadb persisted directory, but forgot to create the instance that actually starts up MariaDB.

Keep in mind that Docker containers die after the command has been executed. Therefore, in order to keep services such as Apache running, we modify the command so they run daemon processes that never die. But if you overwrite `command` and put one that finishes immediately such as `chown`, the container will exit instantly.

It is easy to fix, see an example below:

```
--- wrong-docker-compose.yml	2019-02-21 09:53:05.607323073 +0100
+++ docker-compose.yml	2019-02-21 09:53:38.248326408 +0100
@@ -1,6 +1,6 @@
 version: '2'
 services:
-  mariadb:
+  mariadbPermissions:
     user: root
     command: chown -R 1001:1001 /bitnami/mariadb
     image: 'bitnami/mariadb:latest'
@@ -11,6 +11,17 @@
       - ALLOW_EMPTY_PASSWORD=yes
     volumes:
       - '/directory/piwik/mariadb:/bitnami/mariadb'
+  mariadb:
+    image: 'bitnami/mariadb:latest'
+    environment:
+      - MARIADB_USER=bn_matomo
+      - MARIADB_DATABASE=bitnami_matomo
+      - ALLOW_EMPTY_PASSWORD=yes
+    volumes:
+      - '/directory/piwik/mariadb:/bitnami/mariadb'
+    depends_on:
+      - mariadbPermissions
   matomo:
     image: 'bitnami/matomo:latest'
     environment:
```

**Comment by dchen71** [comment]
Hi @marcosbc, thank you for the really great explanation about overriding the default docker command!

Following your instructions, I have added the permissions service and dependency so matomo can now connect to the database. I can not find the server but cannot connect using the supplied default MARIADB_USER bn_matomo user. I have tried simply changing the username in both the mariadb and matomo environmental variables but that didn't work.  Is there anything else I might be missing?

```
matomo_1              | mysql-c ERROR [canConnect] Connection with 'bn_matomo' user is unsuccessful
matomo_1              | Error executing 'postInstallation': Cannot connect to MySQL server:
matomo_1              | MySQL command failed to run. Error: 
matomo_1              |  ERROR 1130 (HY000): Host '172.18.0.2' is not allowed to connect to this MariaDB server
```

**Comment by marcosbc** [comment]
Hi @dchen71, note that if you want to change the user, you must do it in two places:

- In the MariaDB container (not the mariadbPermissions one): Set `MARIADB_USER` to the new value.
- In the Matomo container: Set `MATOMO_DATABASE_USER` to the new value.

If you've done this and still find issues, please show us your docker-compose.yml file so we can check it.

**Comment by dchen71** [comment]
Thanks a lot for your help. Other than the added mariadbPermissions and ports on matomo, everything else is the default so it should run. 

```
version: '2'
services:
  mariadbPermissions:
    user: root
    command: chown -R 1001:1001 /bitnami/mariadb
    image: 'bitnami/mariadb:latest'
    volumes:
      - '/directory/piwik/mariadb:/bitnami/mariadb'
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - '/directory/piwik/mariadb:/bitnami/mariadb'
    depends_on:
      - mariadbPermissions
  matomo:
    image: 'bitnami/matomo:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
      - '6999:80'
      - '6998:443'
    depends_on:
      - mariadb
    volumes:
      - '/directory/piwik/matomo_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
```
