### ISSUE TITLE
Error in Matomo: Unable to read INI file

### ISSUE THREAD

**Issue by Laul0** [bitnami/bitnami-docker-matomo#31]
**Description**

First execution of the container with appropriate config from my docker composer and I can't use matomo because of an error:

```
[Mon Apr 22 00:05:00.797919 2019] [php7:notice] [pid 174] [client ***.***.*.**:57574] Error in Matomo: Unable to read INI file {/opt/bitnami/matomo/config/config.ini.php}: Syntax error in INI configuration:  Your host may have disabled parse_ini_file().
```

From the web

<img width="864" alt="Screen Shot 2019-04-21 at 20 14 31" src="https://user-images.githubusercontent.com/15279205/56477337-8ca23200-6472-11e9-855c-fb441afec335.png">

**Steps to reproduce the issue:**

Execute docker-compose with the following parameters:

```yaml
version: '3.7'

services:
  matomo:
    image: bitnami/matomo:latest
    container_name: matomo
    networks:
      - mymysqlserver
      - myglobalnetwork
    ports:
      - "80"
      - "443"
    volumes:
      - type: bind
        source: /path/to/my/matomo
        target: /bitnami
    environment:
      - VIRTUAL_HOST=matomo.mydomain.com
      - MARIADB_HOST=mysql
      - MATOMO_DATABASE_NAME=MYSQLDATABSE
      - MATOMO_DATABASE_USER=MYSQLUSER
      - MATOMO_DATABASE_PASSWORD=MYSQLPASSWORD
      - MATOMO_USERNAME=MYUSERLOGIN
      - MATOMO_HOST=matomo
      - MATOMO_PASSWORD=MYUSERPASSWORD
      - MATOMO_EMAIL=matomo@mydomain.com
      - MATOMO_WEBSITE_NAME=MyName
      - MATOMO_WEBSITE_HOST=matomo.mydomain.com
    restart: always

networks:
  mymysqlserver:
    external:
      name: mymysqlserver
  myglobalnetwork:
```

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:48:46 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: "you don't need to know"
 Running: "you don't need to know"
 Paused: 0
 Stopped: 21
Images: "you don't need to know"
Server Version: 18.09.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: "you don't need to know"
runc version: "you don't need to know"
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: "you don't need to know"
Total Memory: "you don't need to know"
Name: "you don't need to know"
ID: "you don't need to know"
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by tompizmor** [comment]
Hi @Laul0,

I am not able to reproduce the issue. Did you make any customization to the `config.ini.php` file? 

I found [this thread](https://forum.matomo.org/t/unable-to-read-ini-file-your-host-may-have-disabled-parse-ini-file/19949/11) in the Matomo forum that might help. Can you take a look?

**Comment by Laul0** [comment]
Hi @tompizmor,

No customization! I just create the docker container from my composer and I have this error...
Thx for your answer. I'll see your link and try again

**Comment by Laul0** [comment]
If I use my local configuration, matomo works:

```
version: '3.7'

services:
  mysql:
    image: mysql:5.7.25
    environment:
      - MYSQL_ROOT_PASSWORD=password01
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - "9010:80"
      - "9011:443"
    environment:
      - PMA_HOST=mysql
    restart: always

  matomo:
    image: bitnami/matomo:latest
    depends_on:
      - mysql
    ports:
      - "9020:80"
      - "9021:443"
    environment:
      - MARIADB_HOST=mysql
      - MARIADB_ROOT_PASSWORD=password01
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_USER=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=password01
      - MATOMO_DATABASE_NAME=matomo
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_PASSWORD=password01
      - MATOMO_USERNAME=matomo
      - MATOMO_HOST=matomo
      - MATOMO_PASSWORD=password01
      - MATOMO_EMAIL=matomo@localhost.fr
      - MATOMO_WEBSITE_NAME=LsOnline
      - MATOMO_WEBSITE_HOST=http://localhost:9020/
    restart: always

networks:
  default:
```

But, in my PROD environment I'm using an nginx proxy... a shared database (tables are created by the setup script)
