### ISSUE TITLE
matomo failing to connect to root user (not able to connect to db)

### ISSUE THREAD

**Issue by amitmohapatra** [bitnami/bitnami-docker-matomo#33]
Hi,

I am facing some some issue with below configuration.

``` services:
  mariadb:
    image: 'bitnami/mariadb:10.2.14'
    environment:
      - MARIADB_ROOT_PASSWORD=matomo123
    volumes:
      - 'mariadb_data:/bitnami'
  matomo:
    image: 'bitnami/matomo:3'
    environment:
      - MATOMO_USERNAME=admin
      - MATOMO_HOST=127.0.0.1
      - MATOMO_PASSWORD=admin
      - MATOMO_EMAIL=user@example.com
      - MATOMO_WEBSITE_NAME=example
      - MATOMO_WEBSITE_HOST=https://example.org
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_HOST=mariadb
      - MARIADB_ROOT_PASSWORD=matomo123
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_USER=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=matomo
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_NAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local 

ERROR:
Status: Downloaded newer image for bitnami/matomo:3
Creating matomodocker_mariadb_1
Creating matomodocker_matomo_1
Attaching to matomodocker_mariadb_1, matomodocker_matomo_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
matomo_1   |
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
matomo_1   | Welcome to the Bitnami matomo container
mariadb_1  |
matomo_1   | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   |
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Persisted data and properties have been restored.
mariadb_1  | mariadb INFO     Any input specified will not take effect.
mariadb_1  | mariadb INFO   This installation requires no credentials.
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 190722 09:12:08 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 190722 09:12:08 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
matomo_1   | nami    INFO  Initializing apache
matomo_1   | nami    INFO  apache successfully initialized
matomo_1   | nami    INFO  Initializing php
matomo_1   | nami    INFO  php successfully initialized
matomo_1   | nami    INFO  Initializing mysql-client
matomo_1   | mysql-c INFO  Trying to connect to MySQL server
matomo_1   | mysql-c INFO  Found MySQL server listening at mariadb:3306
matomo_1   | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
matomo_1   | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
matomo_1   | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
matomo_1   | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
matomo_1   | mysql-c ERROR [canConnect] Connection with 'root' user is unsuccessful
matomo_1   | Error executing 'postInstallation': Cannot connect to MySQL server:
matomo_1   | MySQL command failed to run. Error:
matomo_1   |  ERROR 1045 (28000): Access denied for user 'root'@'172.18.0.3' (using password: YES)
matomo_1   |
matomodocker_matomo_1 exited with code 1

**Comment by alemorcuq** [comment]
Hi, @amitmohapatra.

I can see in the log you already have some persisted data for the `mariadb` container and thus it's restoring it instead of applying your desired configuration:

```
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Persisted data and properties have been restored.
mariadb_1  | mariadb INFO     Any input specified will not take effect.
mariadb_1  | mariadb INFO   This installation requires no credentials.
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
```

It's very likely you have a different root password configured in that volume. If you don't care about the data in that volume, you can bring all containers down and remove the volumes with:

```
$ docker-compose down -v
```

Then `docker-compose up` should make it work.

Regards,
Alejandro

**Comment by amitmohapatra** [comment]
Thanks Its working.

**Comment by amitmohapatra** [comment]
Just wanted to know can i use mysql instead of mariadb. If it is possible then what configuration change do i need in compose file.

**Comment by alemorcuq** [comment]
Hi, @amitmohapatra.

You can try by changing the `mariadb` image with the `mysql` one, but note that we test this image with `mariadb` and not with `mysql`. This is your same `docker-compose.yaml` but with `mysql` instead of `mariadb`:

```
version: '2'
services:
  mysql:
    image: 'bitnami/mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=matomo123
    volumes:
      - 'mysql_data:/bitnami'
  matomo:
    image: 'bitnami/matomo:3'
    environment:
      - MATOMO_USERNAME=admin
      - MATOMO_HOST=127.0.0.1
      - MATOMO_PASSWORD=admin
      - MATOMO_EMAIL=user@example.com
      - MATOMO_WEBSITE_NAME=example
      - MATOMO_WEBSITE_HOST=https://example.org
      - MARIADB_PORT_NUMBER=3306
      - MARIADB_HOST=mysql
      - MARIADB_ROOT_PASSWORD=matomo123
      - MYSQL_CLIENT_CREATE_DATABASE_NAME=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_USER=matomo
      - MYSQL_CLIENT_CREATE_DATABASE_PASSWORD=matomo
      - MATOMO_DATABASE_USER=matomo
      - MATOMO_DATABASE_NAME=matomo
      - MATOMO_DATABASE_PASSWORD=matomo
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mysql
    volumes:
      - 'matomo_data:/bitnami'
volumes:
  mysql_data:
    driver: local
  matomo_data:
    driver: local 
```

Regards,
Alejandro
