### ISSUE TITLE
On matomo container recreate, a memory_limit is reset to 128M in php.ini

### ISSUE THREAD

**Issue by valentinab25** [bitnami/bitnami-docker-matomo#36]
**Description**

Does not matter what is the memory_limit in the /opt/bitnami/php/conf/php.ini, on container re-create, a *memory_limit = 128M* is added at the end of the file.

**Steps to reproduce the issue:**

1. Use this docker-compose.yml ( with a volume for the php configuration )
```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  matomo:
    image: 'bitnami/matomo:3.11.0'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami'
      - matomo_php:/opt/bitnami/php/conf
      - apache:/opt/bitnami/apache/conf
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
  matomo_php:
    driver: local
  apache:
    driver: local
```
2. Modify memory_limit and check it

```
docker exec -it matomo_matomo_1 sed -i 's/memory_limit = .*/memory_limit = 2048M/g' /opt/bitnami/php/conf/php.ini
docker exec -it matomo_matomo_1 grep memory_limit /opt/bitnami/php/conf/php.ini
memory_limit = 2048M
```
3. Force matomo container re-create 
```
docker-compose up --force-recreate -d 
```
4. Check memory_limit
```
docker exec -it matomo_matomo_1 grep memory_limit /opt/bitnami/php/conf/php.ini
memory_limit = 2048M
memory_limit = 128M
```
**Describe the results you received:**
The memory_limit is always reset to 128M 

**Describe the results you expected:**
The memory_limit should remain the one in the php.ini file.

**Additional information you deem important (e.g. issue happens only occasionally):**

From my investigations, the problem happens on `nami_initialize matomo` command, at the moment when it logs:
`matomo  INFO  Preparing PHP environment...`

**Comment by carrodher** [comment]
Hi, thanks for the detailed explanation, this has to do with the configurability of our container. We should allow ways to configure these settings without persisting the specific data.
Unfortunately, at this time, it's not possible, after recreating the container the following parameters are set: 
```yaml
{
  'memory_limit': '128M',
  'upload_max_filesize': '60M',
  'post_max_size': '60M',
  'session.auto_start': '0',
  'always_populate_raw_post_data': '-1',
}
```

I just created an internal task to discuss possible solutions to this issue. We will keep you informed
