### ISSUE TITLE
Issue when upgrade from 3.13.0 to 3.13.1

### ISSUE THREAD

**Issue by Laul0** [bitnami/bitnami-docker-matomo#50]
**Description**

Error after upgrading the latest Docker image of Matomo

**Steps to reproduce the issue:**

1. Docker compose use `latest` version of Matomo
2. Down the previous container
3. Pull latest version of Matomo
4. Up the container with the latest version of the image

**Describe the results you received:**

The Docker container stop after a couple of second.
Here, the container logs when you perform a `up`:

```
Attaching to matomo
matomo    |
matomo    | Welcome to the Bitnami matomo container
matomo    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo    | Send us your feedback at containers@bitnami.com
matomo    |
matomo    | nami    INFO  Initializing apache
matomo    | apache  WARN  The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount configuration files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
matomo    | apache  WARN  Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'...
matomo    | nami    INFO  apache successfully initialized
matomo    | nami    INFO  Initializing php
matomo    | php     WARN  The directory '/bitnami/php/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount configuration files at '/opt/bitnami/php/conf' instead.
matomo    | php     WARN  Restoring configuration at '/bitnami/php/conf' to '/opt/bitnami/php/conf'...
matomo    | nami    INFO  php successfully initialized
matomo    | nami    INFO  Initializing mysql-client
matomo    | nami    INFO  mysql-client successfully initialized
matomo    | nami    INFO  Initializing matomo
matomo    | matomo  INFO  Preparing PHP environment...
matomo    | matomo  INFO  matomo has being already initialized, restoring...
matomo    | Error executing 'postInstallation': The installation of Matomo failed.
```
And the Matomo server never start.

If I change the configuration file path from `/bitnami/php/conf` to `/opt/bitnami/php/conf` , I have this error log:

```
matomo    | /app-entrypoint.sh: line 3: /opt/bitnami/base/functions: No such file or directory
```

**Describe the results you expected:**

Start Matomo server with the latest version.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.5
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        e8ff056dbc
 Built:             Thu Apr 11 04:44:28 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.5
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       e8ff056
  Built:            Thu Apr 11 04:10:53 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

- Output of `docker info`:

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 18.09.5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: ...
runc version: ...
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 15.68GiB
Name: [my server name]
ID: [my server ID]
Docker Root Dir: [path/to/docker/root]
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by miguelaeh** [comment]
Hi @Laul0 ,
We are trying to replicate the issue but we can't, could you please paste your `docker-compose` file?
I guess it could be a problem with the volumes at it is failing restoring the data.

**Comment by Laul0** [comment]
Hi @miguelaeh,

Thx you for your answer. Here, my compose file:

```
version: '3.7'

services:
  matomo:
    image: bitnami/matomo:latest
    container_name: matomo
    networks:
      - mysql
      - default
    ports:
      - "80"
      - "443"
    volumes:
      - type: bind
        source: /path/to/data/matomo
        target: /bitnami
    environment:
      - VIRTUAL_HOST=matomo.mydomain.url
      - MARIADB_HOST=mysql
      - MATOMO_DATABASE_NAME=database_name
      - MATOMO_DATABASE_USER=db_user
      - MATOMO_DATABASE_PASSWORD=db_password
      - MATOMO_USERNAME=matomo-username
      - MATOMO_HOST=MatomoHost
      - MATOMO_PASSWORD=default_matomo_password
      - MATOMO_EMAIL=matomo@email
      - MATOMO_WEBSITE_NAME=WebSiteName
      - MATOMO_WEBSITE_HOST=https://matomowebiste.url
    restart: always

networks:
  mysql:
    external:
      name: mysql
  default:
```
