### ISSUE TITLE
Kubernetes: visits show IP address of ingress, not user

### ISSUE THREAD

**Issue by jobachhu** [bitnami/bitnami-docker-matomo#51]
**Description**

I'm trying to run this image in a Kubernetes cluster behind an nginx-ingress. The ingress receives the client requests and forwards it to the pod, but Matomo isn't configured to the use X-Forwarded-For header and I couldn't find an option to configure it. There seems to be an option to configure `proxy_uri_header` via the `MATOMO_ENABLE_PROXY_URI_HEADER` envvar, but not one to set `proxy_client_headers`.

According to https://matomo.org/faq/how-to-install/faq_98, the following two options would be needed:
```
proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"
proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"
```

I added them to the running container in the `[general]` section of `/opt/bitnami/matomo/config/config.ini.php`, but I couldn't find a way to permanently configure them since this file seems to be created at runtime and contains other configuration, like the database credentials. Is there another way to do it or could we also add an environment variable to conditionally add these config lines similar to `proxy_uri_header`?

Thanks in advance for your help!

**Steps to reproduce the issue:**

1. Apply test.yaml from this repo to create a mariadb and matomo deployment
2. Create an ingress:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-matomo
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - test-matomo.example.com
      secretName: test-matomo.example.com-tls
  rules:
    - host: test-matomo.example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: test-matomo
              servicePort: 80
```
3. configure matomo on a website
4. visit your website
5. Go to Visitors > Visits Log in Matomo and look at the IP

**Describe the results you received:**

The IP address of the visit is that of one of the worker nodes in my cluster, not that of the user.

**Describe the results you expected:**

The IP should be that of the user who sent the original request, taken from the X-Forwarded-For header sent by ingress-nginx

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Probably not environment specific, but the test was run on Kubernetes 1.16.3 launched by rancher 2.3.3 with ingress `rancher/nginx-ingress-controller:nginx-0.25.1-rancher1`. The workers are Ubuntu 18.04.3 LTS with docker version 19.3.5.

**Comment by juan131** [comment]
Hi @jobachhu 

As you said, there' no env var at this moment to modify that settting.

As you can check in the link below, Matomo container will run any script you mount at `/docker-entrypoint-init.d`. Therefore, you can mount your custom script that modifies that (and any other) property in the configuration file.

- https://github.com/bitnami/bitnami-docker-matomo/blob/master/3/debian-10/rootfs/post-init.sh

Would that solution work for you?

**Comment by jobachhu** [comment]
Thanks for your help @juan131, that tip makes the modification much simpler!

I created a slightly adapted Dockerfile that allows enabling the proxy headers via an environment variable:

`Dockerfile`:
```
FROM bitnami/matomo:3

COPY init.d /docker-entrypoint-init.d
```

`init.d/01-set-proxy-variables.sh`:
```
#!/bin/bash

. /opt/bitnami/base/functions

if [[ "$MATOMO_ENABLE_PROXY_HEADERS" =~ ^(yes|Yes|YES)$ ]]; then
  info "Configuring proxy host and client headers"
  sed -i '/^\[General\]$/a proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"' /opt/bitnami/matomo/config/config.ini.php
  sed -i '/^\[General\]$/a proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"' /opt/bitnami/matomo/config/config.ini.php
fi
```

Are there any plans to support more environment variables such as this one? Otherwise it might be nice to document how to easily modify configuration parameters of your choice using the init script.

**Comment by juan131** [comment]
Hi @jobachhu 

> Are there any plans to support more environment variables such as this one? Otherwise it might be nice to document how to easily modify configuration parameters of your choice using the init script

I don't think we should add a specific environment variable for each specific setting users may want to customize. Instead we should make it very easy to add customizations.

That's why I'd suggest that you add to your K8s manifests a way to mount your custom scripts in the Matomo image from a configmap. This way:

- You create a configmap with your customizations scripts
- Then, you mount this configmap at `/docker-entrypoint-init.d` in the Matomo container (you can easily do this adapting the deployment manifest)
- Finally, when you deploy Matomo using the original, it'll detect the scripts and run them

**Comment by Bengrunt** [comment]
Hello,

I believe this customization possibility should be documented somewhere in the `Readme.md` file.
I understand perfectly the idea behind one image fits all but as @juan131 said "[...] we should make it very easy to add customizations." so that means the docs should mention this.

Anyway, regarding this particular issue, I adapted @jobachhu script to my own ends (running Matomo on Openshift 3.11, so my APIs may be fairly old). Here are the code snippets that might help others:

**ConfigMap definition:**
```
apiVersion: v1
data:
  01-set-proxy-variables.sh: |
    #!/bin/bash

    . /opt/bitnami/scripts/liblog.sh

    info "Configuring proxy host and client headers"
    sed -i '/^\[General\]$/a proxy_host_headers[] = "HTTP_X_FORWARDED_HOST"' /opt/bitnami/matomo/config/config.ini.php
    sed -i '/^\[General\]$/a proxy_client_headers[] = "HTTP_X_FORWARDED_FOR"' /opt/bitnami/matomo/config/config.ini.php
kind: ConfigMap
metadata:
  name: matomo-config
```

**Deployment snippets**
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matomo
spec:
  template:
    spec:
      containers:
      - name: matomo
[...]
        volumeMounts:
        - mountPath: /bitnami
          name: matomo-data
        - mountPath: /docker-entrypoint-init.d/01-set-proxy-variables.sh
          name: matomo-config-proxy-vars
          readOnly: true
          subPath: 01-set-proxy-variables.sh
[...]
      volumes:
      - configMap:
          defaultMode: 420
          name: matomo-config
        name: matomo-config-proxy-vars
```

_Note: I dropped completely the idea of using a environment variable to enable this feature since we have to mount a ConfigMap anyway ...._

Cheers !
