### ISSUE TITLE
matomo static files are not stored under mounted volumes

### ISSUE THREAD

**Issue by jkjha** [bitnami/bitnami-docker-matomo#56]
**Description**
I have mounted my persistance volume to the docker image, but it seems the image only stores the config.ini file and plugins at the mounted location. All other static files (/var/www/ content) related to matomo are not stored there. Due to this, I am not able to persists the custom logo for the matomo application. Also I want to use .console script outside of the image for archiving report to run job. But since these are not mounted on the persistance volumes, its not available. 

**Steps to reproduce the issue:**

1. Deploy the container to a decc cluster.
2. Set a custom logo for the matomo application.
3. Destroy the image and redeploy same image.

**Describe the results you received:**

My custom logo, that I uploaded vanishes.

**Describe the results you expected:**

The custom logo should persists and in case of pod restart or redpeploy, it should show my custom logo.

**Additional information you deem important (e.g. issue happens only occasionally):**

Here is my deployment.yml file

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matomo-web
  namespace: scdc1-staging-matomo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: matomo-web
    spec:
      containers:
      - name: matomo-web
        image: docker.io/bitnami/matomo:3-debian-10
        imagePullPolicy: Always
        env:
          - name: MARIADB_HOST
            value: "matomo-mariadb"
          - name: MARIADB_PORT_NUMBER
            value: "3306"
          - name: MARIADB_USER
            value: "non-root"
          - name: MATOMO_DATABASE_USER
            value: "test"
          - name: MATOMO_DATABASE_NAME
            value: "matomo"
          - name: MATOMO_DATABASE_PASSWORD
            value: "**secret**"
          - name: ALLOW_EMPTY_PASSWORD
            value: "no"
          - name: MATOMO_USERNAME
            value: "test"
          - name: MATOMO_PASSWORD
            value: "secret"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          limits:
            memory: 2048Mi
            cpu: 1000m
        volumeMounts:
          - mountPath: /bitnami
            name: matomo-data
      volumes:
        - name: matomo-data
          persistentVolumeClaim:
            claimName: matomo-test-1
```

**Version**

- Output of `docker version`:

```
Docker version 19.03.8, build afacb8b
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 33
  Running: 0
  Paused: 0
  Stopped: 33
 Images: 68
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: EIEQ:JVS7:D3NF:L34R:3D3X:YGCM:SDIR:XTRV:7QN7:E2XG:RNUS:SLAS
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 53
  System Time: 2020-07-19T11:23:16.42345Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
minikube
