### ISSUE TITLE
Error executing 'postInstallation': Types of '/opt/bitnami/matomo/plugins/Tour/config' and '/bitnami/matomo/plugins/Tour' differ

### ISSUE THREAD

**Issue by dguttierrez** [bitnami/bitnami-docker-matomo#58]
I have matomo 3.9.1 and want to upgrade to latest 3.14.

My docker-compose file is:

```yaml
version: '3'
services:
  mariadb:
      image: 'docker.io/bitnami/mariadb:latest'
      networks:
        - matomo
      environment:
        - MARIADB_USER=testnimatomo
        - MARIADB_DATABASE=testni_matomo
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
      volumes:
        - 'mariadb_data:/bitnami'
  matomo:
      image: 'docker.io/bitnami/matomo:latest'
      networks:
        - matomo
      environment:
        - MARIADB_HOST=mariadb
        - MATOMO_DATABASE_USER=testnimatomo
        - MATOMO_DATABASE_NAME=testni_matomo
        - MATOMO_USERNAME=someuser
        - MATOMO_PASSWORD=somepassword
        - ALLOW_EMPTY_PASSWORD=yes
        - MATOMO_WEBSITE_NAME=Matomo Test
      ports:
        - 8081:80
        - 4444:443
      depends_on:
        - mariadb  
      volumes:
        - 'matomo_data:/bitnami'
volumes:
   mariadb_data:
      driver: local
   matomo_data:
      driver: local
networks:
   matomo:
      external: false
```

after runing docker-compose up, error is:
```
Error executing 'postInstallation': Types of '/opt/bitnami/matomo/plugins/Tour/config' and '/bitnami/matomo/plugins/Tour' differ
```

a have also this warning:
```
matomo_1   | apache  WARN  The directory '/bitnami/apache/conf' was externally mounted. This is a legacy configuration and will be deprecated soon. Please mount configuration files at '/opt/bitnami/apache/conf' instead. Find an example at: https://github.com/bitnami/bitnami-docker-apache#full-configuration
matomo_1   | apache  WARN  Restoring configuration at '/bitnami/apache/conf' to '/opt/bitnami/apache/conf'...
matomo_1   | nami    INFO  apache successfully initialized
```
but I think it is not in connection with error.

I have tried on 3 different machines and error is always same: Tried on Linux Docekr CE, Docker For Windows WSL2 and Docker for Mac.
