### ISSUE TITLE
Unable to use MATOMO_USERNAME, MATOMO_PASSWORD

### ISSUE THREAD

**Issue by venomone** [bitnami/bitnami-docker-matomo#62]
Hello,

I'm trying to setup Matomo using  MATOMO_USERNAME and MATOMO_PASSWORD at my docker-compose file.
But for some reason this is not working, the application shows the right data at the console output on startup:

```
Matomo      | matomo  INFO  ########################################################################
Matomo      | matomo  INFO   Installation parameters for matomo:
Matomo      | matomo  INFO     Username: matomo
Matomo      | matomo  INFO     Password: **********
Matomo      | matomo  INFO     email: me@somedomain.de
Matomo      | matomo  INFO   (Passwords are not shown for security reasons)
Matomo      | matomo  INFO  ########################################################################
```
But if I try to login it's not working, I still have to use the default user: User and the default password: bitnami
If I access the container using docker exec and i read the envirnoment vars using printenv everything seems to be set as defined.

I setup my container like so:

```yaml
version: "3.5"

networks:
  frontend:
    internal: false
  backend:
    internal: true

volumes:
  mariadb_data:
    driver: local

services:
  matomo:
    image: 'docker.io/bitnami/matomo:3-debian-10'
    container_name: Matomo
    hostname: Matomo
    environment:
      MATOMO_USERNAME: ${MATOMO_USERNAME}
      MATOMO_PASSWORD: ${MATOMO_PASSWORD}
      MATOMO_EMAIL: ${MATOMO_EMAIL}
      MATOMO_WEBSITE_NAME: ${MATOMO_WEBSITE_NAME}
      MATOMO_WEBSITE_HOST: ${MATOMO_WEBSITE_HOST}
      MATOMO_DATABASE_USER: ${MARIADB_USER}
      MATOMO_DATABASE_PASSWORD: ${MARIADB_PWD}
      MATOMO_DATABASE_NAME: ${MARIADB_DB}
      MARIADB_HOST: ${MARIADB_HOST}
      PHP_MEMORY_LIMIT: 192M
    ports:
      - '80:80'
      - '443:443'
    networks:
      - frontend
      - backend
    volumes:
      - './matomo_root:/bitnami'
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: ${MARIADB_HOST}
    hostname: ${MARIADB_HOST}
    environment:
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PWD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PWD}
    networks:
      - backend
    volumes:
      - ./runtimedata/log/mariadb:/var/log/mysql
      - ./config/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mariadb_data:/var/lib/mysql
```

Any Idea why this is failing?
