### ISSUE TITLE
Cron for auto-archive

### ISSUE THREAD

**Issue by sutidor** [bitnami/bitnami-docker-matomo#75]
**Description**
Since I didnt find a working solution in older closed tickets, here we go.
Trying to setup auto-archive according to [matomo docs](https://matomo.org/docs/setup-auto-archiving)
`5 * * * * daemon /opt/bitnami/php/bin/php /opt/bitnami/matomo/console core:archive >> /var/log/cron.log 2>&1`

I ran it as root once (instead of daemon), but then the directory permissions messed up. The directories `/opt/bitnami/matomo/tmp` and onward are owned by either daemon:root or 1001:root, the former cant be used to login and the latter does not even exist.

How to enable working auto-archiving? Is it even enabled but I simply dont find it?

**Comment by rafariossaa** [comment]
Hi,
  In order to be able to execute cron jobs you will need to run the container a root. cron service needs to be executed as root.
  For this, you will to add `user: root` to the matomo service in the docker-compose:
```
version: "2"
services:
  mariadb:
    image: "docker.io/bitnami/mariadb:10.3-debian-10"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      # Flag necessary for the database max allowed packet check
      # https://matomo.org/faq/troubleshooting/faq_183/
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - "mariadb_data:/bitnami/mariadb"
  matomo:
    image: "docker.io/bitnami/matomo:4-debian-10"
    ports:
      - "80:8080"
      - "443:8443"
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - "matomo_data:/bitnami/matomo"
    depends_on:
      - mariadb
    user: root
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
```
