### ISSUE TITLE
docker-compose does not start container due to permission error related to mkdir "/bitnami/matomo/plugins"

### ISSUE THREAD

**Issue by luixxiul** [bitnami/bitnami-docker-matomo#87]
**Description**

After pulling the latest image, the instance stopped starting up due to:

````
$ docker-compose up matomo
temp_mariadb_1 is up-to-date
Starting temp_matomo_1 ... done
Attaching to temp_matomo_1
matomo_1   | matomo 13:48:49.55 
matomo_1   | matomo 13:48:49.56 Welcome to the Bitnami matomo container
matomo_1   | matomo 13:48:49.56 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo_1   | matomo 13:48:49.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo_1   | matomo 13:48:49.56 
matomo_1   | matomo 13:48:49.57 INFO  ==> ** Starting Matomo setup **
matomo_1   | matomo 13:48:49.60 INFO  ==> Configuring PHP options
matomo_1   | matomo 13:48:49.62 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo_1   | matomo 13:48:49.65 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
matomo_1   | matomo 13:48:49.71 INFO  ==> Persisted Matomo installation detected
matomo_1   | matomo 13:48:49.71 INFO  ==> Updating default plugins in persisted data
matomo_1   | rsync: mkdir "/bitnami/matomo/plugins" failed: Permission denied (13)
matomo_1   | rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]
````

**Steps to reproduce the issue:**

1. `docker pull bitnami/matomo:latest` 
2. `docker-compose up`

**Describe the results you received:**

The instance does not start due to the permission error above.

**Describe the results you expected:**

The instance should start without the error.

**Additional information you deem important (e.g. issue happens only occasionally):**

docker-compose.yml

````
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    restart: unless-stopped
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
    volumes:
      - 'mariadb_data:/bitnami'
  matomo:
    image: 'bitnami/matomo:latest'
    restart: unless-stopped
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MATOMO_USERNAME=example
      - MATOMO_PASSWORD=example
      - MATOMO_EMAIL=example@example.com
      - MATOMO_WEBSITE_NAME='Example'
      - MATOMO_WEBSITE_HOST=https://example.com
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami/matomo'
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local

````

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 5
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.19.0-16-amd64
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 1.948GiB
 Name: tk2-402-42385
 ID: BDDO:SB5F:OKGL:277P:47ZN:BWE3:GCX5:TG2E:IE2H:3MU5:EADP:LUIT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.0, build 0aa59064
docker-py version: 3.7.2
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Looks like https://github.com/bitnami/bitnami-docker-matomo/issues/67#issuecomment-742125706 but not quite sure where to investigate.
