### ISSUE TITLE
Configuration is not writable with securityContext

### ISSUE THREAD

**Issue by tburschka** [bitnami/bitnami-docker-matomo#95]
**Description**

I'm try to run this container in a kubernetes environment and restrict the container via security context (due to the PSP - see below). But as a result the configuration files aren't writeable.

**Steps to reproduce the issue:**

* Create a deployment and apply it:

```yaml
---
# Source: matomo/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matomo
  labels:
    helm.sh/chart: matomo-4.4.0_01
    app.kubernetes.io/name: matomo
    app.kubernetes.io/instance: matomo
    app.kubernetes.io/version: "4.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
      app.kubernetes.io/instance: matomo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/instance: matomo
    spec:
      serviceAccountName: matomo
      securityContext:
        {}
      initContainers:
        - args:
            - for i in {30..0}; do redis-cli -h ${MATOMO_CACHE_HOST} -a ${MATOMO_CACHE_PASSWORD} ping &> /dev/null;
              if [[ $? == 0 ]]; then
              echo "Connection to Redis established."; exit 0; fi;
              echo "Redis init process in progress..."; sleep 1; done;
              echo "No connection to Redis could be established!"; exit 1;
          command:
            - /bin/bash
            - -c
          envFrom:
            - secretRef:
                name: matomo
          image: bitnami/redis
          imagePullPolicy: Always
          name: redis-init
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          resources:
            requests:
              memory: 50Mi
        - args:
            - for i in {30..0}; do mysql -h${MATOMO_DATABASE_HOST} -u${MATOMO_DATABASE_USER} -p${MATOMO_DATABASE_PASSWORD} -N -e "SELECT 1" &> /dev/null;
              if [[ $? == 0 ]]; then
              echo "Connection to MariaDB established."; exit 0; fi;
              echo "MariaDB init process in progress..."; sleep 1; done;
              echo "No connection to MariaDB could be established!"; exit 1;
          command:
            - /bin/bash
            - -c
          envFrom:
            - secretRef:
                name: matomo
          image: bitnami/mariadb
          imagePullPolicy: Always
          name: mariadb-init
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          resources:
            requests:
              memory: 50Mi
      containers:
        - name: matomo
          securityContext:
            capabilities:
              drop:
              - ALL
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
          image: "bitnami/matomo:4.4.0-debian-10-r1"
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: matomo
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
            initialDelaySeconds: 90
          readinessProbe:
            httpGet:
              path: /
              port: https
              scheme: HTTPS
            initialDelaySeconds: 90
          volumeMounts:
            - name: data
              mountPath: "/bitnami"
              subPath: ""
          resources:
            {}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: matomo
```

**Describe the results you received:**

* Log of Pod:
```
matomo 00:49:43.54
matomo 00:49:43.54 Welcome to the Bitnami matomo container
matomo 00:49:43.54 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-matomo
matomo 00:49:43.56 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-matomo/issues
matomo 00:49:43.57
matomo 00:49:43.57 INFO  ==> ** Starting Matomo setup **
matomo 00:49:43.58 WARN  ==> The Apache configuration file '/opt/bitnami/apache/conf/httpd.conf' is not writable. Configurations based on environment variables will not be applied.
matomo 00:49:43.60 INFO  ==> Configuring PHP options
matomo 00:49:43.61 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars
matomo 00:49:43.67 WARN  ==> The matomo virtual host file '/opt/bitnami/apache/conf/vhosts/matomo-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
matomo 00:49:43.67 WARN  ==> The matomo virtual host file '/opt/bitnami/apache/conf/vhosts/matomo-https-vhost.conf' is not writable. Configurations based on environment variables will not be applied for this file.
matomo 00:49:43.68 INFO  ==> Ensuring Matomo directories exist
matomo 00:49:43.68 INFO  ==> Trying to connect to the database server
matomo 00:49:43.70 INFO  ==> Starting apache in background
[Mon Aug 02 00:49:43.754116 2021] [ssl:warn] [pid 67] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 02 00:49:43.754460 2021] [ssl:warn] [pid 67] AH01909: www.example.com:8443:0 server certificate does NOT include an ID which matches the server name
matomo 00:50:43.79 ERROR ==> apache did not start
```

* `ls -lha /opt/bitnami`

```
total 40K
drwxrwxr-x 1 root   root 4.0K Aug  1 16:20 .
drwxrwxr-x 1 root   root 4.0K Aug  1 16:19 ..
-rw-r--r-- 1 root   root 1.8K Aug  1 16:19 .bitnami_components.json
drwxrwxr-x 1 root   root 4.0K Aug  1 16:19 apache
lrwxrwxrwx 1 root   root    6 Aug  1 16:20 apache2 -> apache
drwxr-xr-x 1 root   root 4.0K Jun  7 06:13 common
drwxrwxr-x 2 root   root 4.0K Aug  1 16:19 licenses
drwxrwxr-x 1 daemon root 4.0K Jul 28 13:33 matomo
drwxr-xr-x 1 root   root 4.0K Aug  1 16:20 mysql
drwxr-xr-x 1 root   root 4.0K Jul 24 17:01 php
drwxrwxr-x 1 root   root 4.0K Aug  1 16:19 scripts
```

*  `ls -lha /opt/bitnami/apache/conf/vhosts/`

```
drwxrwxr-x 1 root root 4.0K Aug  1 16:20 .
drwxrwxr-x 1 root root 4.0K Aug  1 16:19 ..
-rw-rw-r-- 1 root root  163 Aug  1 16:20 00_status-vhost.conf
drwxrwxr-x 2 root root 4.0K Aug  1 16:20 htaccess
-rw-rw-r-- 1 root root  420 Aug  1 16:20 matomo-https-vhost.conf
-rw-rw-r-- 1 root root  256 Aug  1 16:20 matomo-vhost.conf
```

**Describe the results you expected:**

It seems that files/directories inside `/opt/bitnami/´ are only writeable as root.

**Additional information you deem important (e.g. issue happens only occasionally):**

* `kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+rke2r1", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-21T16:49:24Z", GoVersion:"go1.16.6b7", Compiler:"gc", Platform:"linux/amd64"}
```

* `kubectl get psp global-restricted-psp -o yaml

```yaml 
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: global-restricted-psp
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  requiredDropCapabilities:
  - ALL
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    ranges:
    - max: 65535
      min: 1
    rule: MustRunAs
  volumes:
  - configMap
  - emptyDir
  - projected
  - secret
  - downwardAPI
  - persistentVolumeClaim
```

* Ubuntu 20.04.2
* Kernel 5.4.0-80-generic
* containerd://1.4.8-k3s1
